### ISSUE TITLE
Minimum password strength

### ISSUE THREAD

**Issue by adamcaudill** [adamcaudill/CurveLock#6]
This one is tricky.

Need to add some type of check to make sure that the user is using a password that isn't complete junk. miniLock uses [zxcvbn](https://github.com/dropbox/zxcvbn), which is great for them, as it's in JS, but for us, we don't have a well accepted library that we can use. 

There is a .NET "port" of zxcvbn, but it's actually executing the JS behind the scenes - the last thing I want to do in a security focused application is add that kind of attack / review / audit surface. So it's not an option.

So, options:

* Do a real port of zxcvbn to C# - Could be useful, but time consuming, time I don't think I have.
* Write something similar, but simpler. Also time consuming.

I think this needs to happen for the first real release, but there's going to be some time investment required.

**Comment by bitbeans** [comment]
I use this: https://github.com/mickford/zxcvbn-cs in one of my projects.
But i don`t see any javascript in it. :)

**Comment by adamcaudill** [comment]
I found that one after I opened this ticket, but I have seriously mixed feelings. One, seems it was written then left untouched - where zxcvbn has been under active development. Next, it add a *lot* of non-standard (i.e. not part of the framework, or well known open source) to the mix. Which means it'll be harder to take a quick look at determine there's nothing funny going on.

This would be the easy way, and this is the major blocker to 0.1, but I don't want to make it harder to review than necessary.

**Comment by bitbeans** [comment]
I only use it to indicate the quality of the password and show the estimated crack time. I don`t restrict any passwords. In my opinion there no perfect way to clear this problem. 

The weakest factor will be the user, if he forget his password (maybe because it`s hard to remember or he don`t use any password manager), he can`t recover it and the encrypted files are lost.

**Comment by bitbeans** [comment]
@adamcaudill  I use **zxcvbn-cs** now also in: https://github.com/bitbeans/NaclKeys/blob/master/NaclKeys/KeyGenerator.cs#L110

**Comment by adamcaudill** [comment]
I went ahead and used `zxcvbn-cs` - it's not enforcing any minimum at this point, but it does use the entropy calculation to provide a score. For now, I think it's good enough. May revisit later, but this was the big hold-up to getting 0.1 released.
